baseURL = 'https://logyj.github.io/'
languageCode = 'zh-cn'
title = 'ğŸ”ç©·å±±è·æµ·ğŸš£â€â™‚ï¸'
theme = "PaperMod"
defaultContentLanguage = "zh"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

#ä½¿ç”¨ä¸»é¡µä¿¡æ¯æ¨¡å¼ï¼Œæ³¨é‡Šæ‰ä¸»é¡µ
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    url = "/"
#    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 45

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 50

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 60

[params]
  ShowToc = true  #æ˜¾ç¤ºåšå®¢é¡µçš„ç›®å½•
  TocOpen = true   #é»˜è®¤æ‰“å¼€åšå®¢é¡µçš„ç›®å½•
  ShowPostNavLinks = true   #åœ¨åšå®¢é¡µé¢åº•éƒ¨æ˜¾ç¤ºå‰ååšå®¢é“¾æ¥
  ShowAllPagesInArchive = true  #æ˜¾ç¤ºæ‰€æœ‰é¡µé¢åœ¨Archiveé¡µé¢åŒ…æ‹¬About Meé¡µ
  ShowPageNums = true  #åœ¨åšå®¢æ–‡ç« åˆ—è¡¨ä¸­æ˜¯å¦æ˜¾ç¤ºé¡µç 
  comments = false   #è¯„è®ºè®¾ç½®æ‰“å¼€åï¼Œéƒ¨ç½²ç½‘é¡µæ²¡æœ‰æ˜¾ç¤ºæ‰€ä»¥å…³é—­
  ShowWordCount = false #åšå®¢å­—æ•°ç»Ÿè®¡æ‰“å¼€åï¼Œéƒ¨ç½²ç½‘é¡µå­—æ•°æ˜¾ç¤ºé”™è¯¯æ‰€ä»¥å…³é—­

[params.profileMode]   # ç®€ä»‹æ¨¡å¼
  enabled = true
  title = "å¿—ä¹‹æ‰€è¶‹æ— è¿œå¼—å±Š ç©·å±±è·æµ·ä¸èƒ½é™ä¹Ÿ"
  subtitle = "ğŸ‘‹ æŠŠå¿ƒä¸­ä¸æ‚¦å…¨éƒ¨æ”¾è¿™é‡Œï¼Œå¸¦å›æ„‰æ‚¦çš„å¿ƒæƒ…å»å¥‹æ–—ï¼ä¸ºäº†è‡ªå·±å’Œå®¶äººä¸€å®šè¦åŠªåŠ›å¥‹æ–—ï¼æŠŠä¸å¥½çš„ä¸€åˆ‡å…¨éƒ¨ç•™åœ¨è¿™é‡Œï¼æ„Ÿè°¢è¿™ä¸ªåƒåœ¾åœºï¼ğŸ˜"
  imageUrl = "/img/homeimage.jpg"
  imageTitle = ""  #å›¾ç‰‡ä¿¡æ¯ä¸æ˜¾ç¤º
  imageWidth = 360   #åœ¨ä¸»é¡µæ­£ä¸­é—´æ˜¾ç¤ºçš„åœ†å½¢å›¾åƒ
  imageHeight = 360

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts/"

[[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive/"

#[[params.socialIcons]]   #ç®€ä»‹æ¨¡å¼ä¸‹ä¸»é¡µä¸ŠæŒ‰é’®ä¸Šæ–¹çš„ç¤¾äº¤é“¾æ¥
#  name = "<platform>"
#  url = "<link>"

#[[params.socialIcons]]   #ç®€ä»‹æ¨¡å¼ä¸‹ä¸»é¡µä¸ŠæŒ‰é’®ä¸Šæ–¹çš„ç¤¾äº¤é“¾æ¥
#  name = "<platform 2>"
#  url = "<link2>"

# ä¸»é¡µä¿¡æ¯æ¨¡å¼-ç›´æ¥åœ¨é¦–é¡µæ˜¾ç¤ºé¡µå¤´ä¿¡æ¯å’ŒHomeé¡µé‡å¤ï¼Œæ‰€ä»¥ä½¿ç”¨Homeé¡µå°±ä¸ç”¨é¦–é¡µä¿¡æ¯ï¼Œä½†æ˜¯ä¸»é¡µä¿¡æ¯çš„å­—ä½“æ›´å¤§ã€‚
# ä¸»é¡µä»‹ç»æ˜¯ç®€è¦ä¿¡æ¯æ¨èä½¿ç”¨ä¸»é¡µä¿¡æ¯æ¨¡å¼ã€‚
# å¦‚æœHomeä¸»é¡µæ”¾çš„å†…å®¹å¤šå°±ç”¨Homeé¡µ
[params.homeInfoParams]
  Title = "å¿—ä¹‹æ‰€è¶‹æ— è¿œå¼—å±Š ç©·å±±è·æµ·ä¸èƒ½é™ä¹Ÿ"
  Content = "ğŸ‘‹ æŠŠå¿ƒä¸­ä¸æ‚¦å…¨éƒ¨æ”¾è¿™é‡Œï¼Œå¸¦å›æ„‰æ‚¦çš„å¿ƒæƒ…å»å¥‹æ–—ï¼ä¸ºäº†è€å©†å’Œå„¿å­ä¸€å®šè¦åŠªåŠ›å¥‹æ–—ï¼æŠŠä¸å¥½çš„ä¸€åˆ‡å…¨éƒ¨ç•™åœ¨è¿™é‡Œï¼æ„Ÿè°¢è¿™ä¸ªåƒåœ¾åœºï¼ğŸ˜"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  